name: Release
on:
  push:
    tags:
      - "*"
jobs:
  call-release-reusable:
    uses: devops-prac1/github-reusable-workflows/.github/workflows/release.yml@main
    with:
      project_name: expense-backend
      npm_install: false
    secrets: inherit